spring:
  profiles:
    active:
    - feign
    
management:
  security:
    enabled: false
    
zuul:
  routes:
    greeting-service:
      path: /lets/**
      serviceId: greeting-service 
  ignored-services:
    greeting-service,html5-client